

if OBJECT_ID('geez') is not null
	drop table geez;

create table dbo.geez(syllable nvarchar(1), 
                      syllable_decimal int, 
					  syllable_v2 nvarchar(1),
					  syllable_hex	nvarchar(10), 
					  Description nvarchar(150),
					  syllable_grouping nvarchar(150)
					  )

insert into geez
select N'ሀ' as syllable,4608 as syllable_decimal, N'ሀ' as syllable_v2,'1200' as syllable_hex,'ETHIOPIC SYLLABLE HA' as Description,'Ethiopic' as grouping union 
select N'ሁ' as syllable,4609 as syllable_decimal, N'ሁ' as syllable_v2,'1201' as syllable_hex,'ETHIOPIC SYLLABLE HU' as Description,'Ethiopic' as grouping union 
select N'ሂ' as syllable,4610 as syllable_decimal, N'ሂ' as syllable_v2,'1202' as syllable_hex,'ETHIOPIC SYLLABLE HI' as Description,'Ethiopic' as grouping union 
select N'ሃ' as syllable,4611 as syllable_decimal, N'ሃ' as syllable_v2,'1203' as syllable_hex,'ETHIOPIC SYLLABLE HAA' as Description,'Ethiopic' as grouping union 
select N'ሄ' as syllable,4612 as syllable_decimal, N'ሄ' as syllable_v2,'1204' as syllable_hex,'ETHIOPIC SYLLABLE HEE' as Description,'Ethiopic' as grouping union 
select N'ህ' as syllable,4613 as syllable_decimal, N'ህ' as syllable_v2,'1205' as syllable_hex,'ETHIOPIC SYLLABLE HE' as Description,'Ethiopic' as grouping union 
select N'ሆ' as syllable,4614 as syllable_decimal, N'ሆ' as syllable_v2,'1206' as syllable_hex,'ETHIOPIC SYLLABLE HO' as Description,'Ethiopic' as grouping union 
select N'ሇ' as syllable,4615 as syllable_decimal, N'ሇ' as syllable_v2,'1207' as syllable_hex,'ETHIOPIC SYLLABLE HOA' as Description,'Ethiopic' as grouping union 
select N'ለ' as syllable,4616 as syllable_decimal, N'ለ' as syllable_v2,'1208' as syllable_hex,'ETHIOPIC SYLLABLE LA' as Description,'Ethiopic' as grouping union 
select N'ሉ' as syllable,4617 as syllable_decimal, N'ሉ' as syllable_v2,'1209' as syllable_hex,'ETHIOPIC SYLLABLE LU' as Description,'Ethiopic' as grouping union 
select N'ሊ' as syllable,4618 as syllable_decimal, N'ሊ' as syllable_v2,'120A' as syllable_hex,'ETHIOPIC SYLLABLE LI' as Description,'Ethiopic' as grouping union 
select N'ላ' as syllable,4619 as syllable_decimal, N'ላ' as syllable_v2,'120B' as syllable_hex,'ETHIOPIC SYLLABLE LAA' as Description,'Ethiopic' as grouping union 
select N'ሌ' as syllable,4620 as syllable_decimal, N'ሌ' as syllable_v2,'120C' as syllable_hex,'ETHIOPIC SYLLABLE LEE' as Description,'Ethiopic' as grouping union 
select N'ል' as syllable,4621 as syllable_decimal, N'ል' as syllable_v2,'120D' as syllable_hex,'ETHIOPIC SYLLABLE LE' as Description,'Ethiopic' as grouping union 
select N'ሎ' as syllable,4622 as syllable_decimal, N'ሎ' as syllable_v2,'120E' as syllable_hex,'ETHIOPIC SYLLABLE LO' as Description,'Ethiopic' as grouping union 
select N'ሏ' as syllable,4623 as syllable_decimal, N'ሏ' as syllable_v2,'120F' as syllable_hex,'ETHIOPIC SYLLABLE LWA' as Description,'Ethiopic' as grouping union 
select N'ሐ' as syllable,4624 as syllable_decimal, N'ሐ' as syllable_v2,'1210' as syllable_hex,'ETHIOPIC SYLLABLE HHA' as Description,'Ethiopic' as grouping union 
select N'ሑ' as syllable,4625 as syllable_decimal, N'ሑ' as syllable_v2,'1211' as syllable_hex,'ETHIOPIC SYLLABLE HHU' as Description,'Ethiopic' as grouping union 
select N'ሒ' as syllable,4626 as syllable_decimal, N'ሒ' as syllable_v2,'1212' as syllable_hex,'ETHIOPIC SYLLABLE HHI' as Description,'Ethiopic' as grouping union 
select N'ሓ' as syllable,4627 as syllable_decimal, N'ሓ' as syllable_v2,'1213' as syllable_hex,'ETHIOPIC SYLLABLE HHAA' as Description,'Ethiopic' as grouping union 
select N'ሔ' as syllable,4628 as syllable_decimal, N'ሔ' as syllable_v2,'1214' as syllable_hex,'ETHIOPIC SYLLABLE HHEE' as Description,'Ethiopic' as grouping union 
select N'ሕ' as syllable,4629 as syllable_decimal, N'ሕ' as syllable_v2,'1215' as syllable_hex,'ETHIOPIC SYLLABLE HHE' as Description,'Ethiopic' as grouping union 
select N'ሖ' as syllable,4630 as syllable_decimal, N'ሖ' as syllable_v2,'1216' as syllable_hex,'ETHIOPIC SYLLABLE HHO' as Description,'Ethiopic' as grouping union 
select N'ሗ' as syllable,4631 as syllable_decimal, N'ሗ' as syllable_v2,'1217' as syllable_hex,'ETHIOPIC SYLLABLE HHWA' as Description,'Ethiopic' as grouping union 
select N'መ' as syllable,4632 as syllable_decimal, N'መ' as syllable_v2,'1218' as syllable_hex,'ETHIOPIC SYLLABLE MA' as Description,'Ethiopic' as grouping union 
select N'ሙ' as syllable,4633 as syllable_decimal, N'ሙ' as syllable_v2,'1219' as syllable_hex,'ETHIOPIC SYLLABLE MU' as Description,'Ethiopic' as grouping union 
select N'ሚ' as syllable,4634 as syllable_decimal, N'ሚ' as syllable_v2,'121A' as syllable_hex,'ETHIOPIC SYLLABLE MI' as Description,'Ethiopic' as grouping union 
select N'ማ' as syllable,4635 as syllable_decimal, N'ማ' as syllable_v2,'121B' as syllable_hex,'ETHIOPIC SYLLABLE MAA' as Description,'Ethiopic' as grouping union 
select N'ሜ' as syllable,4636 as syllable_decimal, N'ሜ' as syllable_v2,'121C' as syllable_hex,'ETHIOPIC SYLLABLE MEE' as Description,'Ethiopic' as grouping union 
select N'ም' as syllable,4637 as syllable_decimal, N'ም' as syllable_v2,'121D' as syllable_hex,'ETHIOPIC SYLLABLE ME' as Description,'Ethiopic' as grouping union 
select N'ሞ' as syllable,4638 as syllable_decimal, N'ሞ' as syllable_v2,'121E' as syllable_hex,'ETHIOPIC SYLLABLE MO' as Description,'Ethiopic' as grouping union 
select N'ሟ' as syllable,4639 as syllable_decimal, N'ሟ' as syllable_v2,'121F' as syllable_hex,'ETHIOPIC SYLLABLE MWA' as Description,'Ethiopic' as grouping union 
select N'ሠ' as syllable,4640 as syllable_decimal, N'ሠ' as syllable_v2,'1220' as syllable_hex,'ETHIOPIC SYLLABLE SZA' as Description,'Ethiopic' as grouping union 
select N'ሡ' as syllable,4641 as syllable_decimal, N'ሡ' as syllable_v2,'1221' as syllable_hex,'ETHIOPIC SYLLABLE SZU' as Description,'Ethiopic' as grouping union 
select N'ሢ' as syllable,4642 as syllable_decimal, N'ሢ' as syllable_v2,'1222' as syllable_hex,'ETHIOPIC SYLLABLE SZI' as Description,'Ethiopic' as grouping union 
select N'ሣ' as syllable,4643 as syllable_decimal, N'ሣ' as syllable_v2,'1223' as syllable_hex,'ETHIOPIC SYLLABLE SZAA' as Description,'Ethiopic' as grouping union 
select N'ሤ' as syllable,4644 as syllable_decimal, N'ሤ' as syllable_v2,'1224' as syllable_hex,'ETHIOPIC SYLLABLE SZEE' as Description,'Ethiopic' as grouping union 
select N'ሥ' as syllable,4645 as syllable_decimal, N'ሥ' as syllable_v2,'1225' as syllable_hex,'ETHIOPIC SYLLABLE SZE' as Description,'Ethiopic' as grouping union 
select N'ሦ' as syllable,4646 as syllable_decimal, N'ሦ' as syllable_v2,'1226' as syllable_hex,'ETHIOPIC SYLLABLE SZO' as Description,'Ethiopic' as grouping union 
select N'ሧ' as syllable,4647 as syllable_decimal, N'ሧ' as syllable_v2,'1227' as syllable_hex,'ETHIOPIC SYLLABLE SZWA' as Description,'Ethiopic' as grouping union 
select N'ረ' as syllable,4648 as syllable_decimal, N'ረ' as syllable_v2,'1228' as syllable_hex,'ETHIOPIC SYLLABLE RA' as Description,'Ethiopic' as grouping union 
select N'ሩ' as syllable,4649 as syllable_decimal, N'ሩ' as syllable_v2,'1229' as syllable_hex,'ETHIOPIC SYLLABLE RU' as Description,'Ethiopic' as grouping union 
select N'ሪ' as syllable,4650 as syllable_decimal, N'ሪ' as syllable_v2,'122A' as syllable_hex,'ETHIOPIC SYLLABLE RI' as Description,'Ethiopic' as grouping union 
select N'ራ' as syllable,4651 as syllable_decimal, N'ራ' as syllable_v2,'122B' as syllable_hex,'ETHIOPIC SYLLABLE RAA' as Description,'Ethiopic' as grouping union 
select N'ሬ' as syllable,4652 as syllable_decimal, N'ሬ' as syllable_v2,'122C' as syllable_hex,'ETHIOPIC SYLLABLE REE' as Description,'Ethiopic' as grouping union 
select N'ር' as syllable,4653 as syllable_decimal, N'ር' as syllable_v2,'122D' as syllable_hex,'ETHIOPIC SYLLABLE RE' as Description,'Ethiopic' as grouping union 
select N'ሮ' as syllable,4654 as syllable_decimal, N'ሮ' as syllable_v2,'122E' as syllable_hex,'ETHIOPIC SYLLABLE RO' as Description,'Ethiopic' as grouping union 
select N'ሯ' as syllable,4655 as syllable_decimal, N'ሯ' as syllable_v2,'122F' as syllable_hex,'ETHIOPIC SYLLABLE RWA' as Description,'Ethiopic' as grouping union 
select N'ሰ' as syllable,4656 as syllable_decimal, N'ሰ' as syllable_v2,'1230' as syllable_hex,'ETHIOPIC SYLLABLE SA' as Description,'Ethiopic' as grouping union 
select N'ሱ' as syllable,4657 as syllable_decimal, N'ሱ' as syllable_v2,'1231' as syllable_hex,'ETHIOPIC SYLLABLE SU' as Description,'Ethiopic' as grouping union 
select N'ሲ' as syllable,4658 as syllable_decimal, N'ሲ' as syllable_v2,'1232' as syllable_hex,'ETHIOPIC SYLLABLE SI' as Description,'Ethiopic' as grouping union 
select N'ሳ' as syllable,4659 as syllable_decimal, N'ሳ' as syllable_v2,'1233' as syllable_hex,'ETHIOPIC SYLLABLE SAA' as Description,'Ethiopic' as grouping union 
select N'ሴ' as syllable,4660 as syllable_decimal, N'ሴ' as syllable_v2,'1234' as syllable_hex,'ETHIOPIC SYLLABLE SEE' as Description,'Ethiopic' as grouping union 
select N'ስ' as syllable,4661 as syllable_decimal, N'ስ' as syllable_v2,'1235' as syllable_hex,'ETHIOPIC SYLLABLE SE' as Description,'Ethiopic' as grouping union 
select N'ሶ' as syllable,4662 as syllable_decimal, N'ሶ' as syllable_v2,'1236' as syllable_hex,'ETHIOPIC SYLLABLE SO' as Description,'Ethiopic' as grouping union 
select N'ሷ' as syllable,4663 as syllable_decimal, N'ሷ' as syllable_v2,'1237' as syllable_hex,'ETHIOPIC SYLLABLE SWA' as Description,'Ethiopic' as grouping union 
select N'ሸ' as syllable,4664 as syllable_decimal, N'ሸ' as syllable_v2,'1238' as syllable_hex,'ETHIOPIC SYLLABLE SHA' as Description,'Ethiopic' as grouping union 
select N'ሹ' as syllable,4665 as syllable_decimal, N'ሹ' as syllable_v2,'1239' as syllable_hex,'ETHIOPIC SYLLABLE SHU' as Description,'Ethiopic' as grouping union 
select N'ሺ' as syllable,4666 as syllable_decimal, N'ሺ' as syllable_v2,'123A' as syllable_hex,'ETHIOPIC SYLLABLE SHI' as Description,'Ethiopic' as grouping union 
select N'ሻ' as syllable,4667 as syllable_decimal, N'ሻ' as syllable_v2,'123B' as syllable_hex,'ETHIOPIC SYLLABLE SHAA' as Description,'Ethiopic' as grouping union 
select N'ሼ' as syllable,4668 as syllable_decimal, N'ሼ' as syllable_v2,'123C' as syllable_hex,'ETHIOPIC SYLLABLE SHEE' as Description,'Ethiopic' as grouping union 
select N'ሽ' as syllable,4669 as syllable_decimal, N'ሽ' as syllable_v2,'123D' as syllable_hex,'ETHIOPIC SYLLABLE SHE' as Description,'Ethiopic' as grouping union 
select N'ሾ' as syllable,4670 as syllable_decimal, N'ሾ' as syllable_v2,'123E' as syllable_hex,'ETHIOPIC SYLLABLE SHO' as Description,'Ethiopic' as grouping union 
select N'ሿ' as syllable,4671 as syllable_decimal, N'ሿ' as syllable_v2,'123F' as syllable_hex,'ETHIOPIC SYLLABLE SHWA' as Description,'Ethiopic' as grouping union 
select N'ቀ' as syllable,4672 as syllable_decimal, N'ቀ' as syllable_v2,'1240' as syllable_hex,'ETHIOPIC SYLLABLE QA' as Description,'Ethiopic' as grouping union 
select N'ቁ' as syllable,4673 as syllable_decimal, N'ቁ' as syllable_v2,'1241' as syllable_hex,'ETHIOPIC SYLLABLE QU' as Description,'Ethiopic' as grouping union 
select N'ቂ' as syllable,4674 as syllable_decimal, N'ቂ' as syllable_v2,'1242' as syllable_hex,'ETHIOPIC SYLLABLE QI' as Description,'Ethiopic' as grouping union 
select N'ቃ' as syllable,4675 as syllable_decimal, N'ቃ' as syllable_v2,'1243' as syllable_hex,'ETHIOPIC SYLLABLE QAA' as Description,'Ethiopic' as grouping union 
select N'ቄ' as syllable,4676 as syllable_decimal, N'ቄ' as syllable_v2,'1244' as syllable_hex,'ETHIOPIC SYLLABLE QEE' as Description,'Ethiopic' as grouping union 
select N'ቅ' as syllable,4677 as syllable_decimal, N'ቅ' as syllable_v2,'1245' as syllable_hex,'ETHIOPIC SYLLABLE QE' as Description,'Ethiopic' as grouping union 
select N'ቆ' as syllable,4678 as syllable_decimal, N'ቆ' as syllable_v2,'1246' as syllable_hex,'ETHIOPIC SYLLABLE QO' as Description,'Ethiopic' as grouping union 
select N'ቇ' as syllable,4679 as syllable_decimal, N'ቇ' as syllable_v2,'1247' as syllable_hex,'ETHIOPIC SYLLABLE QOA' as Description,'Ethiopic' as grouping union 
select N'ቈ' as syllable,4680 as syllable_decimal, N'ቈ' as syllable_v2,'1248' as syllable_hex,'ETHIOPIC SYLLABLE QWA' as Description,'Ethiopic' as grouping union 
select N'ቊ' as syllable,4682 as syllable_decimal, N'ቊ' as syllable_v2,'124A' as syllable_hex,'ETHIOPIC SYLLABLE QWI' as Description,'Ethiopic' as grouping union 
select N'ቋ' as syllable,4683 as syllable_decimal, N'ቋ' as syllable_v2,'124B' as syllable_hex,'ETHIOPIC SYLLABLE QWAA' as Description,'Ethiopic' as grouping union 
select N'ቌ' as syllable,4684 as syllable_decimal, N'ቌ' as syllable_v2,'124C' as syllable_hex,'ETHIOPIC SYLLABLE QWEE' as Description,'Ethiopic' as grouping union 
select N'ቍ' as syllable,4685 as syllable_decimal, N'ቍ' as syllable_v2,'124D' as syllable_hex,'ETHIOPIC SYLLABLE QWE' as Description,'Ethiopic' as grouping union 
select N'ቐ' as syllable,4688 as syllable_decimal, N'ቐ' as syllable_v2,'1250' as syllable_hex,'ETHIOPIC SYLLABLE QHA' as Description,'Ethiopic' as grouping union 
select N'ቑ' as syllable,4689 as syllable_decimal, N'ቑ' as syllable_v2,'1251' as syllable_hex,'ETHIOPIC SYLLABLE QHU' as Description,'Ethiopic' as grouping union 
select N'ቒ' as syllable,4690 as syllable_decimal, N'ቒ' as syllable_v2,'1252' as syllable_hex,'ETHIOPIC SYLLABLE QHI' as Description,'Ethiopic' as grouping union 
select N'ቓ' as syllable,4691 as syllable_decimal, N'ቓ' as syllable_v2,'1253' as syllable_hex,'ETHIOPIC SYLLABLE QHAA' as Description,'Ethiopic' as grouping union 
select N'ቔ' as syllable,4692 as syllable_decimal, N'ቔ' as syllable_v2,'1254' as syllable_hex,'ETHIOPIC SYLLABLE QHEE' as Description,'Ethiopic' as grouping union 
select N'ቕ' as syllable,4693 as syllable_decimal, N'ቕ' as syllable_v2,'1255' as syllable_hex,'ETHIOPIC SYLLABLE QHE' as Description,'Ethiopic' as grouping union 
select N'ቖ' as syllable,4694 as syllable_decimal, N'ቖ' as syllable_v2,'1256' as syllable_hex,'ETHIOPIC SYLLABLE QHO' as Description,'Ethiopic' as grouping union 
select N'ቘ' as syllable,4696 as syllable_decimal, N'ቘ' as syllable_v2,'1258' as syllable_hex,'ETHIOPIC SYLLABLE QHWA' as Description,'Ethiopic' as grouping union 
select N'ቚ' as syllable,4698 as syllable_decimal, N'ቚ' as syllable_v2,'125A' as syllable_hex,'ETHIOPIC SYLLABLE QHWI' as Description,'Ethiopic' as grouping union 
select N'ቛ' as syllable,4699 as syllable_decimal, N'ቛ' as syllable_v2,'125B' as syllable_hex,'ETHIOPIC SYLLABLE QHWAA' as Description,'Ethiopic' as grouping union 
select N'ቜ' as syllable,4700 as syllable_decimal, N'ቜ' as syllable_v2,'125C' as syllable_hex,'ETHIOPIC SYLLABLE QHWEE' as Description,'Ethiopic' as grouping union 
select N'ቝ' as syllable,4701 as syllable_decimal, N'ቝ' as syllable_v2,'125D' as syllable_hex,'ETHIOPIC SYLLABLE QHWE' as Description,'Ethiopic' as grouping union 
select N'በ' as syllable,4704 as syllable_decimal, N'በ' as syllable_v2,'1260' as syllable_hex,'ETHIOPIC SYLLABLE BA' as Description,'Ethiopic' as grouping union 
select N'ቡ' as syllable,4705 as syllable_decimal, N'ቡ' as syllable_v2,'1261' as syllable_hex,'ETHIOPIC SYLLABLE BU' as Description,'Ethiopic' as grouping union 
select N'ቢ' as syllable,4706 as syllable_decimal, N'ቢ' as syllable_v2,'1262' as syllable_hex,'ETHIOPIC SYLLABLE BI' as Description,'Ethiopic' as grouping union 
select N'ባ' as syllable,4707 as syllable_decimal, N'ባ' as syllable_v2,'1263' as syllable_hex,'ETHIOPIC SYLLABLE BAA' as Description,'Ethiopic' as grouping union 
select N'ቤ' as syllable,4708 as syllable_decimal, N'ቤ' as syllable_v2,'1264' as syllable_hex,'ETHIOPIC SYLLABLE BEE' as Description,'Ethiopic' as grouping union 
select N'ብ' as syllable,4709 as syllable_decimal, N'ብ' as syllable_v2,'1265' as syllable_hex,'ETHIOPIC SYLLABLE BE' as Description,'Ethiopic' as grouping union 
select N'ቦ' as syllable,4710 as syllable_decimal, N'ቦ' as syllable_v2,'1266' as syllable_hex,'ETHIOPIC SYLLABLE BO' as Description,'Ethiopic' as grouping union 
select N'ቧ' as syllable,4711 as syllable_decimal, N'ቧ' as syllable_v2,'1267' as syllable_hex,'ETHIOPIC SYLLABLE BWA' as Description,'Ethiopic' as grouping union 
select N'ቨ' as syllable,4712 as syllable_decimal, N'ቨ' as syllable_v2,'1268' as syllable_hex,'ETHIOPIC SYLLABLE VA' as Description,'Ethiopic' as grouping union 
select N'ቩ' as syllable,4713 as syllable_decimal, N'ቩ' as syllable_v2,'1269' as syllable_hex,'ETHIOPIC SYLLABLE VU' as Description,'Ethiopic' as grouping union 
select N'ቪ' as syllable,4714 as syllable_decimal, N'ቪ' as syllable_v2,'126A' as syllable_hex,'ETHIOPIC SYLLABLE VI' as Description,'Ethiopic' as grouping union 
select N'ቫ' as syllable,4715 as syllable_decimal, N'ቫ' as syllable_v2,'126B' as syllable_hex,'ETHIOPIC SYLLABLE VAA' as Description,'Ethiopic' as grouping union 
select N'ቬ' as syllable,4716 as syllable_decimal, N'ቬ' as syllable_v2,'126C' as syllable_hex,'ETHIOPIC SYLLABLE VEE' as Description,'Ethiopic' as grouping union 
select N'ቭ' as syllable,4717 as syllable_decimal, N'ቭ' as syllable_v2,'126D' as syllable_hex,'ETHIOPIC SYLLABLE VE' as Description,'Ethiopic' as grouping union 
select N'ቮ' as syllable,4718 as syllable_decimal, N'ቮ' as syllable_v2,'126E' as syllable_hex,'ETHIOPIC SYLLABLE VO' as Description,'Ethiopic' as grouping union 
select N'ቯ' as syllable,4719 as syllable_decimal, N'ቯ' as syllable_v2,'126F' as syllable_hex,'ETHIOPIC SYLLABLE VWA' as Description,'Ethiopic' as grouping union 
select N'ተ' as syllable,4720 as syllable_decimal, N'ተ' as syllable_v2,'1270' as syllable_hex,'ETHIOPIC SYLLABLE TA' as Description,'Ethiopic' as grouping union 
select N'ቱ' as syllable,4721 as syllable_decimal, N'ቱ' as syllable_v2,'1271' as syllable_hex,'ETHIOPIC SYLLABLE TU' as Description,'Ethiopic' as grouping union 
select N'ቲ' as syllable,4722 as syllable_decimal, N'ቲ' as syllable_v2,'1272' as syllable_hex,'ETHIOPIC SYLLABLE TI' as Description,'Ethiopic' as grouping union 
select N'ታ' as syllable,4723 as syllable_decimal, N'ታ' as syllable_v2,'1273' as syllable_hex,'ETHIOPIC SYLLABLE TAA' as Description,'Ethiopic' as grouping union 
select N'ቴ' as syllable,4724 as syllable_decimal, N'ቴ' as syllable_v2,'1274' as syllable_hex,'ETHIOPIC SYLLABLE TEE' as Description,'Ethiopic' as grouping union 
select N'ት' as syllable,4725 as syllable_decimal, N'ት' as syllable_v2,'1275' as syllable_hex,'ETHIOPIC SYLLABLE TE' as Description,'Ethiopic' as grouping union 
select N'ቶ' as syllable,4726 as syllable_decimal, N'ቶ' as syllable_v2,'1276' as syllable_hex,'ETHIOPIC SYLLABLE TO' as Description,'Ethiopic' as grouping union 
select N'ቷ' as syllable,4727 as syllable_decimal, N'ቷ' as syllable_v2,'1277' as syllable_hex,'ETHIOPIC SYLLABLE TWA' as Description,'Ethiopic' as grouping union 
select N'ቸ' as syllable,4728 as syllable_decimal, N'ቸ' as syllable_v2,'1278' as syllable_hex,'ETHIOPIC SYLLABLE CA' as Description,'Ethiopic' as grouping union 
select N'ቹ' as syllable,4729 as syllable_decimal, N'ቹ' as syllable_v2,'1279' as syllable_hex,'ETHIOPIC SYLLABLE CU' as Description,'Ethiopic' as grouping union 
select N'ቺ' as syllable,4730 as syllable_decimal, N'ቺ' as syllable_v2,'127A' as syllable_hex,'ETHIOPIC SYLLABLE CI' as Description,'Ethiopic' as grouping union 
select N'ቻ' as syllable,4731 as syllable_decimal, N'ቻ' as syllable_v2,'127B' as syllable_hex,'ETHIOPIC SYLLABLE CAA' as Description,'Ethiopic' as grouping union 
select N'ቼ' as syllable,4732 as syllable_decimal, N'ቼ' as syllable_v2,'127C' as syllable_hex,'ETHIOPIC SYLLABLE CEE' as Description,'Ethiopic' as grouping union 
select N'ች' as syllable,4733 as syllable_decimal, N'ች' as syllable_v2,'127D' as syllable_hex,'ETHIOPIC SYLLABLE CE' as Description,'Ethiopic' as grouping union 
select N'ቾ' as syllable,4734 as syllable_decimal, N'ቾ' as syllable_v2,'127E' as syllable_hex,'ETHIOPIC SYLLABLE CO' as Description,'Ethiopic' as grouping union 
select N'ቿ' as syllable,4735 as syllable_decimal, N'ቿ' as syllable_v2,'127F' as syllable_hex,'ETHIOPIC SYLLABLE CWA' as Description,'Ethiopic' as grouping union 
select N'ኀ' as syllable,4736 as syllable_decimal, N'ኀ' as syllable_v2,'1280' as syllable_hex,'ETHIOPIC SYLLABLE XA' as Description,'Ethiopic' as grouping union 
select N'ኁ' as syllable,4737 as syllable_decimal, N'ኁ' as syllable_v2,'1281' as syllable_hex,'ETHIOPIC SYLLABLE XU' as Description,'Ethiopic' as grouping union 
select N'ኂ' as syllable,4738 as syllable_decimal, N'ኂ' as syllable_v2,'1282' as syllable_hex,'ETHIOPIC SYLLABLE XI' as Description,'Ethiopic' as grouping union 
select N'ኃ' as syllable,4739 as syllable_decimal, N'ኃ' as syllable_v2,'1283' as syllable_hex,'ETHIOPIC SYLLABLE XAA' as Description,'Ethiopic' as grouping union 
select N'ኄ' as syllable,4740 as syllable_decimal, N'ኄ' as syllable_v2,'1284' as syllable_hex,'ETHIOPIC SYLLABLE XEE' as Description,'Ethiopic' as grouping union 
select N'ኅ' as syllable,4741 as syllable_decimal, N'ኅ' as syllable_v2,'1285' as syllable_hex,'ETHIOPIC SYLLABLE XE' as Description,'Ethiopic' as grouping union 
select N'ኆ' as syllable,4742 as syllable_decimal, N'ኆ' as syllable_v2,'1286' as syllable_hex,'ETHIOPIC SYLLABLE XO' as Description,'Ethiopic' as grouping union 
select N'ኇ' as syllable,4743 as syllable_decimal, N'ኇ' as syllable_v2,'1287' as syllable_hex,'ETHIOPIC SYLLABLE XOA' as Description,'Ethiopic' as grouping union 
select N'ኈ' as syllable,4744 as syllable_decimal, N'ኈ' as syllable_v2,'1288' as syllable_hex,'ETHIOPIC SYLLABLE XWA' as Description,'Ethiopic' as grouping union 
select N'ኊ' as syllable,4746 as syllable_decimal, N'ኊ' as syllable_v2,'128A' as syllable_hex,'ETHIOPIC SYLLABLE XWI' as Description,'Ethiopic' as grouping union 
select N'ኋ' as syllable,4747 as syllable_decimal, N'ኋ' as syllable_v2,'128B' as syllable_hex,'ETHIOPIC SYLLABLE XWAA' as Description,'Ethiopic' as grouping union 
select N'ኌ' as syllable,4748 as syllable_decimal, N'ኌ' as syllable_v2,'128C' as syllable_hex,'ETHIOPIC SYLLABLE XWEE' as Description,'Ethiopic' as grouping union 
select N'ኍ' as syllable,4749 as syllable_decimal, N'ኍ' as syllable_v2,'128D' as syllable_hex,'ETHIOPIC SYLLABLE XWE' as Description,'Ethiopic' as grouping union 
select N'ነ' as syllable,4752 as syllable_decimal, N'ነ' as syllable_v2,'1290' as syllable_hex,'ETHIOPIC SYLLABLE NA' as Description,'Ethiopic' as grouping union 
select N'ኑ' as syllable,4753 as syllable_decimal, N'ኑ' as syllable_v2,'1291' as syllable_hex,'ETHIOPIC SYLLABLE NU' as Description,'Ethiopic' as grouping union 
select N'ኒ' as syllable,4754 as syllable_decimal, N'ኒ' as syllable_v2,'1292' as syllable_hex,'ETHIOPIC SYLLABLE NI' as Description,'Ethiopic' as grouping union 
select N'ና' as syllable,4755 as syllable_decimal, N'ና' as syllable_v2,'1293' as syllable_hex,'ETHIOPIC SYLLABLE NAA' as Description,'Ethiopic' as grouping union 
select N'ኔ' as syllable,4756 as syllable_decimal, N'ኔ' as syllable_v2,'1294' as syllable_hex,'ETHIOPIC SYLLABLE NEE' as Description,'Ethiopic' as grouping union 
select N'ን' as syllable,4757 as syllable_decimal, N'ን' as syllable_v2,'1295' as syllable_hex,'ETHIOPIC SYLLABLE NE' as Description,'Ethiopic' as grouping union 
select N'ኖ' as syllable,4758 as syllable_decimal, N'ኖ' as syllable_v2,'1296' as syllable_hex,'ETHIOPIC SYLLABLE NO' as Description,'Ethiopic' as grouping union 
select N'ኗ' as syllable,4759 as syllable_decimal, N'ኗ' as syllable_v2,'1297' as syllable_hex,'ETHIOPIC SYLLABLE NWA' as Description,'Ethiopic' as grouping union 
select N'ኘ' as syllable,4760 as syllable_decimal, N'ኘ' as syllable_v2,'1298' as syllable_hex,'ETHIOPIC SYLLABLE NYA' as Description,'Ethiopic' as grouping union 
select N'ኙ' as syllable,4761 as syllable_decimal, N'ኙ' as syllable_v2,'1299' as syllable_hex,'ETHIOPIC SYLLABLE NYU' as Description,'Ethiopic' as grouping union 
select N'ኚ' as syllable,4762 as syllable_decimal, N'ኚ' as syllable_v2,'129A' as syllable_hex,'ETHIOPIC SYLLABLE NYI' as Description,'Ethiopic' as grouping union 
select N'ኛ' as syllable,4763 as syllable_decimal, N'ኛ' as syllable_v2,'129B' as syllable_hex,'ETHIOPIC SYLLABLE NYAA' as Description,'Ethiopic' as grouping union 
select N'ኜ' as syllable,4764 as syllable_decimal, N'ኜ' as syllable_v2,'129C' as syllable_hex,'ETHIOPIC SYLLABLE NYEE' as Description,'Ethiopic' as grouping union 
select N'ኝ' as syllable,4765 as syllable_decimal, N'ኝ' as syllable_v2,'129D' as syllable_hex,'ETHIOPIC SYLLABLE NYE' as Description,'Ethiopic' as grouping union 
select N'ኞ' as syllable,4766 as syllable_decimal, N'ኞ' as syllable_v2,'129E' as syllable_hex,'ETHIOPIC SYLLABLE NYO' as Description,'Ethiopic' as grouping union 
select N'ኟ' as syllable,4767 as syllable_decimal, N'ኟ' as syllable_v2,'129F' as syllable_hex,'ETHIOPIC SYLLABLE NYWA' as Description,'Ethiopic' as grouping union 
select N'አ' as syllable,4768 as syllable_decimal, N'አ' as syllable_v2,'12A0' as syllable_hex,'ETHIOPIC SYLLABLE GLOTTAL A' as Description,'Ethiopic' as grouping union 
select N'ኡ' as syllable,4769 as syllable_decimal, N'ኡ' as syllable_v2,'12A1' as syllable_hex,'ETHIOPIC SYLLABLE GLOTTAL U' as Description,'Ethiopic' as grouping union 
select N'ኢ' as syllable,4770 as syllable_decimal, N'ኢ' as syllable_v2,'12A2' as syllable_hex,'ETHIOPIC SYLLABLE GLOTTAL I' as Description,'Ethiopic' as grouping union 
select N'ኣ' as syllable,4771 as syllable_decimal, N'ኣ' as syllable_v2,'12A3' as syllable_hex,'ETHIOPIC SYLLABLE GLOTTAL AA' as Description,'Ethiopic' as grouping union 
select N'ኤ' as syllable,4772 as syllable_decimal, N'ኤ' as syllable_v2,'12A4' as syllable_hex,'ETHIOPIC SYLLABLE GLOTTAL EE' as Description,'Ethiopic' as grouping union 
select N'እ' as syllable,4773 as syllable_decimal, N'እ' as syllable_v2,'12A5' as syllable_hex,'ETHIOPIC SYLLABLE GLOTTAL E' as Description,'Ethiopic' as grouping union 
select N'ኦ' as syllable,4774 as syllable_decimal, N'ኦ' as syllable_v2,'12A6' as syllable_hex,'ETHIOPIC SYLLABLE GLOTTAL O' as Description,'Ethiopic' as grouping union 
select N'ኧ' as syllable,4775 as syllable_decimal, N'ኧ' as syllable_v2,'12A7' as syllable_hex,'ETHIOPIC SYLLABLE GLOTTAL WA' as Description,'Ethiopic' as grouping union 
select N'ከ' as syllable,4776 as syllable_decimal, N'ከ' as syllable_v2,'12A8' as syllable_hex,'ETHIOPIC SYLLABLE KA' as Description,'Ethiopic' as grouping union 
select N'ኩ' as syllable,4777 as syllable_decimal, N'ኩ' as syllable_v2,'12A9' as syllable_hex,'ETHIOPIC SYLLABLE KU' as Description,'Ethiopic' as grouping union 
select N'ኪ' as syllable,4778 as syllable_decimal, N'ኪ' as syllable_v2,'12AA' as syllable_hex,'ETHIOPIC SYLLABLE KI' as Description,'Ethiopic' as grouping union 
select N'ካ' as syllable,4779 as syllable_decimal, N'ካ' as syllable_v2,'12AB' as syllable_hex,'ETHIOPIC SYLLABLE KAA' as Description,'Ethiopic' as grouping union 
select N'ኬ' as syllable,4780 as syllable_decimal, N'ኬ' as syllable_v2,'12AC' as syllable_hex,'ETHIOPIC SYLLABLE KEE' as Description,'Ethiopic' as grouping union 
select N'ክ' as syllable,4781 as syllable_decimal, N'ክ' as syllable_v2,'12AD' as syllable_hex,'ETHIOPIC SYLLABLE KE' as Description,'Ethiopic' as grouping union 
select N'ኮ' as syllable,4782 as syllable_decimal, N'ኮ' as syllable_v2,'12AE' as syllable_hex,'ETHIOPIC SYLLABLE KO' as Description,'Ethiopic' as grouping union 
select N'ኯ' as syllable,4783 as syllable_decimal, N'ኯ' as syllable_v2,'12AF' as syllable_hex,'ETHIOPIC SYLLABLE KOA' as Description,'Ethiopic' as grouping union 
select N'ኰ' as syllable,4784 as syllable_decimal, N'ኰ' as syllable_v2,'12B0' as syllable_hex,'ETHIOPIC SYLLABLE KWA' as Description,'Ethiopic' as grouping union 
select N'ኲ' as syllable,4786 as syllable_decimal, N'ኲ' as syllable_v2,'12B2' as syllable_hex,'ETHIOPIC SYLLABLE KWI' as Description,'Ethiopic' as grouping union 
select N'ኳ' as syllable,4787 as syllable_decimal, N'ኳ' as syllable_v2,'12B3' as syllable_hex,'ETHIOPIC SYLLABLE KWAA' as Description,'Ethiopic' as grouping union 
select N'ኴ' as syllable,4788 as syllable_decimal, N'ኴ' as syllable_v2,'12B4' as syllable_hex,'ETHIOPIC SYLLABLE KWEE' as Description,'Ethiopic' as grouping union 
select N'ኵ' as syllable,4789 as syllable_decimal, N'ኵ' as syllable_v2,'12B5' as syllable_hex,'ETHIOPIC SYLLABLE KWE' as Description,'Ethiopic' as grouping union 
select N'ኸ' as syllable,4792 as syllable_decimal, N'ኸ' as syllable_v2,'12B8' as syllable_hex,'ETHIOPIC SYLLABLE KXA' as Description,'Ethiopic' as grouping union 
select N'ኹ' as syllable,4793 as syllable_decimal, N'ኹ' as syllable_v2,'12B9' as syllable_hex,'ETHIOPIC SYLLABLE KXU' as Description,'Ethiopic' as grouping union 
select N'ኺ' as syllable,4794 as syllable_decimal, N'ኺ' as syllable_v2,'12BA' as syllable_hex,'ETHIOPIC SYLLABLE KXI' as Description,'Ethiopic' as grouping union 
select N'ኻ' as syllable,4795 as syllable_decimal, N'ኻ' as syllable_v2,'12BB' as syllable_hex,'ETHIOPIC SYLLABLE KXAA' as Description,'Ethiopic' as grouping union 
select N'ኼ' as syllable,4796 as syllable_decimal, N'ኼ' as syllable_v2,'12BC' as syllable_hex,'ETHIOPIC SYLLABLE KXEE' as Description,'Ethiopic' as grouping union 
select N'ኽ' as syllable,4797 as syllable_decimal, N'ኽ' as syllable_v2,'12BD' as syllable_hex,'ETHIOPIC SYLLABLE KXE' as Description,'Ethiopic' as grouping union 
select N'ኾ' as syllable,4798 as syllable_decimal, N'ኾ' as syllable_v2,'12BE' as syllable_hex,'ETHIOPIC SYLLABLE KXO' as Description,'Ethiopic' as grouping union 
select N'ዀ' as syllable,4800 as syllable_decimal, N'ዀ' as syllable_v2,'12C0' as syllable_hex,'ETHIOPIC SYLLABLE KXWA' as Description,'Ethiopic' as grouping union 
select N'ዂ' as syllable,4802 as syllable_decimal, N'ዂ' as syllable_v2,'12C2' as syllable_hex,'ETHIOPIC SYLLABLE KXWI' as Description,'Ethiopic' as grouping union 
select N'ዃ' as syllable,4803 as syllable_decimal, N'ዃ' as syllable_v2,'12C3' as syllable_hex,'ETHIOPIC SYLLABLE KXWAA' as Description,'Ethiopic' as grouping union 
select N'ዄ' as syllable,4804 as syllable_decimal, N'ዄ' as syllable_v2,'12C4' as syllable_hex,'ETHIOPIC SYLLABLE KXWEE' as Description,'Ethiopic' as grouping union 
select N'ዅ' as syllable,4805 as syllable_decimal, N'ዅ' as syllable_v2,'12C5' as syllable_hex,'ETHIOPIC SYLLABLE KXWE' as Description,'Ethiopic' as grouping union 
select N'ወ' as syllable,4808 as syllable_decimal, N'ወ' as syllable_v2,'12C8' as syllable_hex,'ETHIOPIC SYLLABLE WA' as Description,'Ethiopic' as grouping union 
select N'ዉ' as syllable,4809 as syllable_decimal, N'ዉ' as syllable_v2,'12C9' as syllable_hex,'ETHIOPIC SYLLABLE WU' as Description,'Ethiopic' as grouping union 
select N'ዊ' as syllable,4810 as syllable_decimal, N'ዊ' as syllable_v2,'12CA' as syllable_hex,'ETHIOPIC SYLLABLE WI' as Description,'Ethiopic' as grouping union 
select N'ዋ' as syllable,4811 as syllable_decimal, N'ዋ' as syllable_v2,'12CB' as syllable_hex,'ETHIOPIC SYLLABLE WAA' as Description,'Ethiopic' as grouping union 
select N'ዌ' as syllable,4812 as syllable_decimal, N'ዌ' as syllable_v2,'12CC' as syllable_hex,'ETHIOPIC SYLLABLE WEE' as Description,'Ethiopic' as grouping union 
select N'ው' as syllable,4813 as syllable_decimal, N'ው' as syllable_v2,'12CD' as syllable_hex,'ETHIOPIC SYLLABLE WE' as Description,'Ethiopic' as grouping union 
select N'ዎ' as syllable,4814 as syllable_decimal, N'ዎ' as syllable_v2,'12CE' as syllable_hex,'ETHIOPIC SYLLABLE WO' as Description,'Ethiopic' as grouping union 
select N'ዏ' as syllable,4815 as syllable_decimal, N'ዏ' as syllable_v2,'12CF' as syllable_hex,'ETHIOPIC SYLLABLE WOA' as Description,'Ethiopic' as grouping union 
select N'ዐ' as syllable,4816 as syllable_decimal, N'ዐ' as syllable_v2,'12D0' as syllable_hex,'ETHIOPIC SYLLABLE PHARYNGEAL A' as Description,'Ethiopic' as grouping union 
select N'ዑ' as syllable,4817 as syllable_decimal, N'ዑ' as syllable_v2,'12D1' as syllable_hex,'ETHIOPIC SYLLABLE PHARYNGEAL U' as Description,'Ethiopic' as grouping union 
select N'ዒ' as syllable,4818 as syllable_decimal, N'ዒ' as syllable_v2,'12D2' as syllable_hex,'ETHIOPIC SYLLABLE PHARYNGEAL I' as Description,'Ethiopic' as grouping union 
select N'ዓ' as syllable,4819 as syllable_decimal, N'ዓ' as syllable_v2,'12D3' as syllable_hex,'ETHIOPIC SYLLABLE PHARYNGEAL AA' as Description,'Ethiopic' as grouping union 
select N'ዔ' as syllable,4820 as syllable_decimal, N'ዔ' as syllable_v2,'12D4' as syllable_hex,'ETHIOPIC SYLLABLE PHARYNGEAL EE' as Description,'Ethiopic' as grouping union 
select N'ዕ' as syllable,4821 as syllable_decimal, N'ዕ' as syllable_v2,'12D5' as syllable_hex,'ETHIOPIC SYLLABLE PHARYNGEAL E' as Description,'Ethiopic' as grouping union 
select N'ዖ' as syllable,4822 as syllable_decimal, N'ዖ' as syllable_v2,'12D6' as syllable_hex,'ETHIOPIC SYLLABLE PHARYNGEAL O' as Description,'Ethiopic' as grouping union 
select N'ዘ' as syllable,4824 as syllable_decimal, N'ዘ' as syllable_v2,'12D8' as syllable_hex,'ETHIOPIC SYLLABLE ZA' as Description,'Ethiopic' as grouping union 
select N'ዙ' as syllable,4825 as syllable_decimal, N'ዙ' as syllable_v2,'12D9' as syllable_hex,'ETHIOPIC SYLLABLE ZU' as Description,'Ethiopic' as grouping union 
select N'ዚ' as syllable,4826 as syllable_decimal, N'ዚ' as syllable_v2,'12DA' as syllable_hex,'ETHIOPIC SYLLABLE ZI' as Description,'Ethiopic' as grouping union 
select N'ዛ' as syllable,4827 as syllable_decimal, N'ዛ' as syllable_v2,'12DB' as syllable_hex,'ETHIOPIC SYLLABLE ZAA' as Description,'Ethiopic' as grouping union 
select N'ዜ' as syllable,4828 as syllable_decimal, N'ዜ' as syllable_v2,'12DC' as syllable_hex,'ETHIOPIC SYLLABLE ZEE' as Description,'Ethiopic' as grouping union 
select N'ዝ' as syllable,4829 as syllable_decimal, N'ዝ' as syllable_v2,'12DD' as syllable_hex,'ETHIOPIC SYLLABLE ZE' as Description,'Ethiopic' as grouping union 
select N'ዞ' as syllable,4830 as syllable_decimal, N'ዞ' as syllable_v2,'12DE' as syllable_hex,'ETHIOPIC SYLLABLE ZO' as Description,'Ethiopic' as grouping union 
select N'ዟ' as syllable,4831 as syllable_decimal, N'ዟ' as syllable_v2,'12DF' as syllable_hex,'ETHIOPIC SYLLABLE ZWA' as Description,'Ethiopic' as grouping union 
select N'ዠ' as syllable,4832 as syllable_decimal, N'ዠ' as syllable_v2,'12E0' as syllable_hex,'ETHIOPIC SYLLABLE ZHA' as Description,'Ethiopic' as grouping union 
select N'ዡ' as syllable,4833 as syllable_decimal, N'ዡ' as syllable_v2,'12E1' as syllable_hex,'ETHIOPIC SYLLABLE ZHU' as Description,'Ethiopic' as grouping union 
select N'ዢ' as syllable,4834 as syllable_decimal, N'ዢ' as syllable_v2,'12E2' as syllable_hex,'ETHIOPIC SYLLABLE ZHI' as Description,'Ethiopic' as grouping union 
select N'ዣ' as syllable,4835 as syllable_decimal, N'ዣ' as syllable_v2,'12E3' as syllable_hex,'ETHIOPIC SYLLABLE ZHAA' as Description,'Ethiopic' as grouping union 
select N'ዤ' as syllable,4836 as syllable_decimal, N'ዤ' as syllable_v2,'12E4' as syllable_hex,'ETHIOPIC SYLLABLE ZHEE' as Description,'Ethiopic' as grouping union 
select N'ዥ' as syllable,4837 as syllable_decimal, N'ዥ' as syllable_v2,'12E5' as syllable_hex,'ETHIOPIC SYLLABLE ZHE' as Description,'Ethiopic' as grouping union 
select N'ዦ' as syllable,4838 as syllable_decimal, N'ዦ' as syllable_v2,'12E6' as syllable_hex,'ETHIOPIC SYLLABLE ZHO' as Description,'Ethiopic' as grouping union 
select N'ዧ' as syllable,4839 as syllable_decimal, N'ዧ' as syllable_v2,'12E7' as syllable_hex,'ETHIOPIC SYLLABLE ZHWA' as Description,'Ethiopic' as grouping union 
select N'የ' as syllable,4840 as syllable_decimal, N'የ' as syllable_v2,'12E8' as syllable_hex,'ETHIOPIC SYLLABLE YA' as Description,'Ethiopic' as grouping union 
select N'ዩ' as syllable,4841 as syllable_decimal, N'ዩ' as syllable_v2,'12E9' as syllable_hex,'ETHIOPIC SYLLABLE YU' as Description,'Ethiopic' as grouping union 
select N'ዪ' as syllable,4842 as syllable_decimal, N'ዪ' as syllable_v2,'12EA' as syllable_hex,'ETHIOPIC SYLLABLE YI' as Description,'Ethiopic' as grouping union 
select N'ያ' as syllable,4843 as syllable_decimal, N'ያ' as syllable_v2,'12EB' as syllable_hex,'ETHIOPIC SYLLABLE YAA' as Description,'Ethiopic' as grouping union 
select N'ዬ' as syllable,4844 as syllable_decimal, N'ዬ' as syllable_v2,'12EC' as syllable_hex,'ETHIOPIC SYLLABLE YEE' as Description,'Ethiopic' as grouping union 
select N'ይ' as syllable,4845 as syllable_decimal, N'ይ' as syllable_v2,'12ED' as syllable_hex,'ETHIOPIC SYLLABLE YE' as Description,'Ethiopic' as grouping union 
select N'ዮ' as syllable,4846 as syllable_decimal, N'ዮ' as syllable_v2,'12EE' as syllable_hex,'ETHIOPIC SYLLABLE YO' as Description,'Ethiopic' as grouping union 
select N'ዯ' as syllable,4847 as syllable_decimal, N'ዯ' as syllable_v2,'12EF' as syllable_hex,'ETHIOPIC SYLLABLE YOA' as Description,'Ethiopic' as grouping union 
select N'ደ' as syllable,4848 as syllable_decimal, N'ደ' as syllable_v2,'12F0' as syllable_hex,'ETHIOPIC SYLLABLE DA' as Description,'Ethiopic' as grouping union 
select N'ዱ' as syllable,4849 as syllable_decimal, N'ዱ' as syllable_v2,'12F1' as syllable_hex,'ETHIOPIC SYLLABLE DU' as Description,'Ethiopic' as grouping union 
select N'ዲ' as syllable,4850 as syllable_decimal, N'ዲ' as syllable_v2,'12F2' as syllable_hex,'ETHIOPIC SYLLABLE DI' as Description,'Ethiopic' as grouping union 
select N'ዳ' as syllable,4851 as syllable_decimal, N'ዳ' as syllable_v2,'12F3' as syllable_hex,'ETHIOPIC SYLLABLE DAA' as Description,'Ethiopic' as grouping union 
select N'ዴ' as syllable,4852 as syllable_decimal, N'ዴ' as syllable_v2,'12F4' as syllable_hex,'ETHIOPIC SYLLABLE DEE' as Description,'Ethiopic' as grouping union 
select N'ድ' as syllable,4853 as syllable_decimal, N'ድ' as syllable_v2,'12F5' as syllable_hex,'ETHIOPIC SYLLABLE DE' as Description,'Ethiopic' as grouping union 
select N'ዶ' as syllable,4854 as syllable_decimal, N'ዶ' as syllable_v2,'12F6' as syllable_hex,'ETHIOPIC SYLLABLE DO' as Description,'Ethiopic' as grouping union 
select N'ዷ' as syllable,4855 as syllable_decimal, N'ዷ' as syllable_v2,'12F7' as syllable_hex,'ETHIOPIC SYLLABLE DWA' as Description,'Ethiopic' as grouping union 
select N'ዸ' as syllable,4856 as syllable_decimal, N'ዸ' as syllable_v2,'12F8' as syllable_hex,'ETHIOPIC SYLLABLE DDA' as Description,'Ethiopic' as grouping union 
select N'ዹ' as syllable,4857 as syllable_decimal, N'ዹ' as syllable_v2,'12F9' as syllable_hex,'ETHIOPIC SYLLABLE DDU' as Description,'Ethiopic' as grouping union 
select N'ዺ' as syllable,4858 as syllable_decimal, N'ዺ' as syllable_v2,'12FA' as syllable_hex,'ETHIOPIC SYLLABLE DDI' as Description,'Ethiopic' as grouping union 
select N'ዻ' as syllable,4859 as syllable_decimal, N'ዻ' as syllable_v2,'12FB' as syllable_hex,'ETHIOPIC SYLLABLE DDAA' as Description,'Ethiopic' as grouping union 
select N'ዼ' as syllable,4860 as syllable_decimal, N'ዼ' as syllable_v2,'12FC' as syllable_hex,'ETHIOPIC SYLLABLE DDEE' as Description,'Ethiopic' as grouping union 
select N'ዽ' as syllable,4861 as syllable_decimal, N'ዽ' as syllable_v2,'12FD' as syllable_hex,'ETHIOPIC SYLLABLE DDE' as Description,'Ethiopic' as grouping union 
select N'ዾ' as syllable,4862 as syllable_decimal, N'ዾ' as syllable_v2,'12FE' as syllable_hex,'ETHIOPIC SYLLABLE DDO' as Description,'Ethiopic' as grouping union 
select N'ዿ' as syllable,4863 as syllable_decimal, N'ዿ' as syllable_v2,'12FF' as syllable_hex,'ETHIOPIC SYLLABLE DDWA' as Description,'Ethiopic' as grouping union 
select N'ጀ' as syllable,4864 as syllable_decimal, N'ጀ' as syllable_v2,'1300' as syllable_hex,'ETHIOPIC SYLLABLE JA' as Description,'Ethiopic' as grouping union 
select N'ጁ' as syllable,4865 as syllable_decimal, N'ጁ' as syllable_v2,'1301' as syllable_hex,'ETHIOPIC SYLLABLE JU' as Description,'Ethiopic' as grouping union 
select N'ጂ' as syllable,4866 as syllable_decimal, N'ጂ' as syllable_v2,'1302' as syllable_hex,'ETHIOPIC SYLLABLE JI' as Description,'Ethiopic' as grouping union 
select N'ጃ' as syllable,4867 as syllable_decimal, N'ጃ' as syllable_v2,'1303' as syllable_hex,'ETHIOPIC SYLLABLE JAA' as Description,'Ethiopic' as grouping union 
select N'ጄ' as syllable,4868 as syllable_decimal, N'ጄ' as syllable_v2,'1304' as syllable_hex,'ETHIOPIC SYLLABLE JEE' as Description,'Ethiopic' as grouping union 
select N'ጅ' as syllable,4869 as syllable_decimal, N'ጅ' as syllable_v2,'1305' as syllable_hex,'ETHIOPIC SYLLABLE JE' as Description,'Ethiopic' as grouping union 
select N'ጆ' as syllable,4870 as syllable_decimal, N'ጆ' as syllable_v2,'1306' as syllable_hex,'ETHIOPIC SYLLABLE JO' as Description,'Ethiopic' as grouping union 
select N'ጇ' as syllable,4871 as syllable_decimal, N'ጇ' as syllable_v2,'1307' as syllable_hex,'ETHIOPIC SYLLABLE JWA' as Description,'Ethiopic' as grouping union 
select N'ገ' as syllable,4872 as syllable_decimal, N'ገ' as syllable_v2,'1308' as syllable_hex,'ETHIOPIC SYLLABLE GA' as Description,'Ethiopic' as grouping union 
select N'ጉ' as syllable,4873 as syllable_decimal, N'ጉ' as syllable_v2,'1309' as syllable_hex,'ETHIOPIC SYLLABLE GU' as Description,'Ethiopic' as grouping union 
select N'ጊ' as syllable,4874 as syllable_decimal, N'ጊ' as syllable_v2,'130A' as syllable_hex,'ETHIOPIC SYLLABLE GI' as Description,'Ethiopic' as grouping union 
select N'ጋ' as syllable,4875 as syllable_decimal, N'ጋ' as syllable_v2,'130B' as syllable_hex,'ETHIOPIC SYLLABLE GAA' as Description,'Ethiopic' as grouping union 
select N'ጌ' as syllable,4876 as syllable_decimal, N'ጌ' as syllable_v2,'130C' as syllable_hex,'ETHIOPIC SYLLABLE GEE' as Description,'Ethiopic' as grouping union 
select N'ግ' as syllable,4877 as syllable_decimal, N'ግ' as syllable_v2,'130D' as syllable_hex,'ETHIOPIC SYLLABLE GE' as Description,'Ethiopic' as grouping union 
select N'ጎ' as syllable,4878 as syllable_decimal, N'ጎ' as syllable_v2,'130E' as syllable_hex,'ETHIOPIC SYLLABLE GO' as Description,'Ethiopic' as grouping union 
select N'ጏ' as syllable,4879 as syllable_decimal, N'ጏ' as syllable_v2,'130F' as syllable_hex,'ETHIOPIC SYLLABLE GOA' as Description,'Ethiopic' as grouping union 
select N'ጐ' as syllable,4880 as syllable_decimal, N'ጐ' as syllable_v2,'1310' as syllable_hex,'ETHIOPIC SYLLABLE GWA' as Description,'Ethiopic' as grouping union 
select N'ጒ' as syllable,4882 as syllable_decimal, N'ጒ' as syllable_v2,'1312' as syllable_hex,'ETHIOPIC SYLLABLE GWI' as Description,'Ethiopic' as grouping union 
select N'ጓ' as syllable,4883 as syllable_decimal, N'ጓ' as syllable_v2,'1313' as syllable_hex,'ETHIOPIC SYLLABLE GWAA' as Description,'Ethiopic' as grouping union 
select N'ጔ' as syllable,4884 as syllable_decimal, N'ጔ' as syllable_v2,'1314' as syllable_hex,'ETHIOPIC SYLLABLE GWEE' as Description,'Ethiopic' as grouping union 
select N'ጕ' as syllable,4885 as syllable_decimal, N'ጕ' as syllable_v2,'1315' as syllable_hex,'ETHIOPIC SYLLABLE GWE' as Description,'Ethiopic' as grouping union 
select N'ጘ' as syllable,4888 as syllable_decimal, N'ጘ' as syllable_v2,'1318' as syllable_hex,'ETHIOPIC SYLLABLE GGA' as Description,'Ethiopic' as grouping union 
select N'ጙ' as syllable,4889 as syllable_decimal, N'ጙ' as syllable_v2,'1319' as syllable_hex,'ETHIOPIC SYLLABLE GGU' as Description,'Ethiopic' as grouping union 
select N'ጚ' as syllable,4890 as syllable_decimal, N'ጚ' as syllable_v2,'131A' as syllable_hex,'ETHIOPIC SYLLABLE GGI' as Description,'Ethiopic' as grouping union 
select N'ጛ' as syllable,4891 as syllable_decimal, N'ጛ' as syllable_v2,'131B' as syllable_hex,'ETHIOPIC SYLLABLE GGAA' as Description,'Ethiopic' as grouping union 
select N'ጜ' as syllable,4892 as syllable_decimal, N'ጜ' as syllable_v2,'131C' as syllable_hex,'ETHIOPIC SYLLABLE GGEE' as Description,'Ethiopic' as grouping union 
select N'ጝ' as syllable,4893 as syllable_decimal, N'ጝ' as syllable_v2,'131D' as syllable_hex,'ETHIOPIC SYLLABLE GGE' as Description,'Ethiopic' as grouping union 
select N'ጞ' as syllable,4894 as syllable_decimal, N'ጞ' as syllable_v2,'131E' as syllable_hex,'ETHIOPIC SYLLABLE GGO' as Description,'Ethiopic' as grouping union 
select N'ጟ' as syllable,4895 as syllable_decimal, N'ጟ' as syllable_v2,'131F' as syllable_hex,'ETHIOPIC SYLLABLE GGWAA' as Description,'Ethiopic' as grouping union 
select N'ጠ' as syllable,4896 as syllable_decimal, N'ጠ' as syllable_v2,'1320' as syllable_hex,'ETHIOPIC SYLLABLE THA' as Description,'Ethiopic' as grouping union 
select N'ጡ' as syllable,4897 as syllable_decimal, N'ጡ' as syllable_v2,'1321' as syllable_hex,'ETHIOPIC SYLLABLE THU' as Description,'Ethiopic' as grouping union 
select N'ጢ' as syllable,4898 as syllable_decimal, N'ጢ' as syllable_v2,'1322' as syllable_hex,'ETHIOPIC SYLLABLE THI' as Description,'Ethiopic' as grouping union 
select N'ጣ' as syllable,4899 as syllable_decimal, N'ጣ' as syllable_v2,'1323' as syllable_hex,'ETHIOPIC SYLLABLE THAA' as Description,'Ethiopic' as grouping union 
select N'ጤ' as syllable,4900 as syllable_decimal, N'ጤ' as syllable_v2,'1324' as syllable_hex,'ETHIOPIC SYLLABLE THEE' as Description,'Ethiopic' as grouping union 
select N'ጥ' as syllable,4901 as syllable_decimal, N'ጥ' as syllable_v2,'1325' as syllable_hex,'ETHIOPIC SYLLABLE THE' as Description,'Ethiopic' as grouping union 
select N'ጦ' as syllable,4902 as syllable_decimal, N'ጦ' as syllable_v2,'1326' as syllable_hex,'ETHIOPIC SYLLABLE THO' as Description,'Ethiopic' as grouping union 
select N'ጧ' as syllable,4903 as syllable_decimal, N'ጧ' as syllable_v2,'1327' as syllable_hex,'ETHIOPIC SYLLABLE THWA' as Description,'Ethiopic' as grouping union 
select N'ጨ' as syllable,4904 as syllable_decimal, N'ጨ' as syllable_v2,'1328' as syllable_hex,'ETHIOPIC SYLLABLE CHA' as Description,'Ethiopic' as grouping union 
select N'ጩ' as syllable,4905 as syllable_decimal, N'ጩ' as syllable_v2,'1329' as syllable_hex,'ETHIOPIC SYLLABLE CHU' as Description,'Ethiopic' as grouping union 
select N'ጪ' as syllable,4906 as syllable_decimal, N'ጪ' as syllable_v2,'132A' as syllable_hex,'ETHIOPIC SYLLABLE CHI' as Description,'Ethiopic' as grouping union 
select N'ጫ' as syllable,4907 as syllable_decimal, N'ጫ' as syllable_v2,'132B' as syllable_hex,'ETHIOPIC SYLLABLE CHAA' as Description,'Ethiopic' as grouping union 
select N'ጬ' as syllable,4908 as syllable_decimal, N'ጬ' as syllable_v2,'132C' as syllable_hex,'ETHIOPIC SYLLABLE CHEE' as Description,'Ethiopic' as grouping union 
select N'ጭ' as syllable,4909 as syllable_decimal, N'ጭ' as syllable_v2,'132D' as syllable_hex,'ETHIOPIC SYLLABLE CHE' as Description,'Ethiopic' as grouping union 
select N'ጮ' as syllable,4910 as syllable_decimal, N'ጮ' as syllable_v2,'132E' as syllable_hex,'ETHIOPIC SYLLABLE CHO' as Description,'Ethiopic' as grouping union 
select N'ጯ' as syllable,4911 as syllable_decimal, N'ጯ' as syllable_v2,'132F' as syllable_hex,'ETHIOPIC SYLLABLE CHWA' as Description,'Ethiopic' as grouping union 
select N'ጰ' as syllable,4912 as syllable_decimal, N'ጰ' as syllable_v2,'1330' as syllable_hex,'ETHIOPIC SYLLABLE PHA' as Description,'Ethiopic' as grouping union 
select N'ጱ' as syllable,4913 as syllable_decimal, N'ጱ' as syllable_v2,'1331' as syllable_hex,'ETHIOPIC SYLLABLE PHU' as Description,'Ethiopic' as grouping union 
select N'ጲ' as syllable,4914 as syllable_decimal, N'ጲ' as syllable_v2,'1332' as syllable_hex,'ETHIOPIC SYLLABLE PHI' as Description,'Ethiopic' as grouping union 
select N'ጳ' as syllable,4915 as syllable_decimal, N'ጳ' as syllable_v2,'1333' as syllable_hex,'ETHIOPIC SYLLABLE PHAA' as Description,'Ethiopic' as grouping union 
select N'ጴ' as syllable,4916 as syllable_decimal, N'ጴ' as syllable_v2,'1334' as syllable_hex,'ETHIOPIC SYLLABLE PHEE' as Description,'Ethiopic' as grouping union 
select N'ጵ' as syllable,4917 as syllable_decimal, N'ጵ' as syllable_v2,'1335' as syllable_hex,'ETHIOPIC SYLLABLE PHE' as Description,'Ethiopic' as grouping union 
select N'ጶ' as syllable,4918 as syllable_decimal, N'ጶ' as syllable_v2,'1336' as syllable_hex,'ETHIOPIC SYLLABLE PHO' as Description,'Ethiopic' as grouping union 
select N'ጷ' as syllable,4919 as syllable_decimal, N'ጷ' as syllable_v2,'1337' as syllable_hex,'ETHIOPIC SYLLABLE PHWA' as Description,'Ethiopic' as grouping union 
select N'ጸ' as syllable,4920 as syllable_decimal, N'ጸ' as syllable_v2,'1338' as syllable_hex,'ETHIOPIC SYLLABLE TSA' as Description,'Ethiopic' as grouping union 
select N'ጹ' as syllable,4921 as syllable_decimal, N'ጹ' as syllable_v2,'1339' as syllable_hex,'ETHIOPIC SYLLABLE TSU' as Description,'Ethiopic' as grouping union 
select N'ጺ' as syllable,4922 as syllable_decimal, N'ጺ' as syllable_v2,'133A' as syllable_hex,'ETHIOPIC SYLLABLE TSI' as Description,'Ethiopic' as grouping union 
select N'ጻ' as syllable,4923 as syllable_decimal, N'ጻ' as syllable_v2,'133B' as syllable_hex,'ETHIOPIC SYLLABLE TSAA' as Description,'Ethiopic' as grouping union 
select N'ጼ' as syllable,4924 as syllable_decimal, N'ጼ' as syllable_v2,'133C' as syllable_hex,'ETHIOPIC SYLLABLE TSEE' as Description,'Ethiopic' as grouping union 
select N'ጽ' as syllable,4925 as syllable_decimal, N'ጽ' as syllable_v2,'133D' as syllable_hex,'ETHIOPIC SYLLABLE TSE' as Description,'Ethiopic' as grouping union 
select N'ጾ' as syllable,4926 as syllable_decimal, N'ጾ' as syllable_v2,'133E' as syllable_hex,'ETHIOPIC SYLLABLE TSO' as Description,'Ethiopic' as grouping union 
select N'ጿ' as syllable,4927 as syllable_decimal, N'ጿ' as syllable_v2,'133F' as syllable_hex,'ETHIOPIC SYLLABLE TSWA' as Description,'Ethiopic' as grouping union 
select N'ፀ' as syllable,4928 as syllable_decimal, N'ፀ' as syllable_v2,'1340' as syllable_hex,'ETHIOPIC SYLLABLE TZA' as Description,'Ethiopic' as grouping union 
select N'ፁ' as syllable,4929 as syllable_decimal, N'ፁ' as syllable_v2,'1341' as syllable_hex,'ETHIOPIC SYLLABLE TZU' as Description,'Ethiopic' as grouping union 
select N'ፂ' as syllable,4930 as syllable_decimal, N'ፂ' as syllable_v2,'1342' as syllable_hex,'ETHIOPIC SYLLABLE TZI' as Description,'Ethiopic' as grouping union 
select N'ፃ' as syllable,4931 as syllable_decimal, N'ፃ' as syllable_v2,'1343' as syllable_hex,'ETHIOPIC SYLLABLE TZAA' as Description,'Ethiopic' as grouping union 
select N'ፄ' as syllable,4932 as syllable_decimal, N'ፄ' as syllable_v2,'1344' as syllable_hex,'ETHIOPIC SYLLABLE TZEE' as Description,'Ethiopic' as grouping union 
select N'ፅ' as syllable,4933 as syllable_decimal, N'ፅ' as syllable_v2,'1345' as syllable_hex,'ETHIOPIC SYLLABLE TZE' as Description,'Ethiopic' as grouping union 
select N'ፆ' as syllable,4934 as syllable_decimal, N'ፆ' as syllable_v2,'1346' as syllable_hex,'ETHIOPIC SYLLABLE TZO' as Description,'Ethiopic' as grouping union 
select N'ፇ' as syllable,4935 as syllable_decimal, N'ፇ' as syllable_v2,'1347' as syllable_hex,'ETHIOPIC SYLLABLE TZOA' as Description,'Ethiopic' as grouping union 
select N'ፈ' as syllable,4936 as syllable_decimal, N'ፈ' as syllable_v2,'1348' as syllable_hex,'ETHIOPIC SYLLABLE FA' as Description,'Ethiopic' as grouping union 
select N'ፉ' as syllable,4937 as syllable_decimal, N'ፉ' as syllable_v2,'1349' as syllable_hex,'ETHIOPIC SYLLABLE FU' as Description,'Ethiopic' as grouping union 
select N'ፊ' as syllable,4938 as syllable_decimal, N'ፊ' as syllable_v2,'134A' as syllable_hex,'ETHIOPIC SYLLABLE FI' as Description,'Ethiopic' as grouping union 
select N'ፋ' as syllable,4939 as syllable_decimal, N'ፋ' as syllable_v2,'134B' as syllable_hex,'ETHIOPIC SYLLABLE FAA' as Description,'Ethiopic' as grouping union 
select N'ፌ' as syllable,4940 as syllable_decimal, N'ፌ' as syllable_v2,'134C' as syllable_hex,'ETHIOPIC SYLLABLE FEE' as Description,'Ethiopic' as grouping union 
select N'ፍ' as syllable,4941 as syllable_decimal, N'ፍ' as syllable_v2,'134D' as syllable_hex,'ETHIOPIC SYLLABLE FE' as Description,'Ethiopic' as grouping union 
select N'ፎ' as syllable,4942 as syllable_decimal, N'ፎ' as syllable_v2,'134E' as syllable_hex,'ETHIOPIC SYLLABLE FO' as Description,'Ethiopic' as grouping union 
select N'ፏ' as syllable,4943 as syllable_decimal, N'ፏ' as syllable_v2,'134F' as syllable_hex,'ETHIOPIC SYLLABLE FWA' as Description,'Ethiopic' as grouping union 
select N'ፐ' as syllable,4944 as syllable_decimal, N'ፐ' as syllable_v2,'1350' as syllable_hex,'ETHIOPIC SYLLABLE PA' as Description,'Ethiopic' as grouping union 
select N'ፑ' as syllable,4945 as syllable_decimal, N'ፑ' as syllable_v2,'1351' as syllable_hex,'ETHIOPIC SYLLABLE PU' as Description,'Ethiopic' as grouping union 
select N'ፒ' as syllable,4946 as syllable_decimal, N'ፒ' as syllable_v2,'1352' as syllable_hex,'ETHIOPIC SYLLABLE PI' as Description,'Ethiopic' as grouping union 
select N'ፓ' as syllable,4947 as syllable_decimal, N'ፓ' as syllable_v2,'1353' as syllable_hex,'ETHIOPIC SYLLABLE PAA' as Description,'Ethiopic' as grouping union 
select N'ፔ' as syllable,4948 as syllable_decimal, N'ፔ' as syllable_v2,'1354' as syllable_hex,'ETHIOPIC SYLLABLE PEE' as Description,'Ethiopic' as grouping union 
select N'ፕ' as syllable,4949 as syllable_decimal, N'ፕ' as syllable_v2,'1355' as syllable_hex,'ETHIOPIC SYLLABLE PE' as Description,'Ethiopic' as grouping union 
select N'ፖ' as syllable,4950 as syllable_decimal, N'ፖ' as syllable_v2,'1356' as syllable_hex,'ETHIOPIC SYLLABLE PO' as Description,'Ethiopic' as grouping union 
select N'ፗ' as syllable,4951 as syllable_decimal, N'ፗ' as syllable_v2,'1357' as syllable_hex,'ETHIOPIC SYLLABLE PWA' as Description,'Ethiopic' as grouping union 
select N'ፘ' as syllable,4952 as syllable_decimal, N'ፘ' as syllable_v2,'1358' as syllable_hex,'ETHIOPIC SYLLABLE RYA' as Description,'Ethiopic' as grouping union 
select N'ፙ' as syllable,4953 as syllable_decimal, N'ፙ' as syllable_v2,'1359' as syllable_hex,'ETHIOPIC SYLLABLE MYA' as Description,'Ethiopic' as grouping union 
select N'ፚ' as syllable,4954 as syllable_decimal, N'ፚ' as syllable_v2,'135A' as syllable_hex,'ETHIOPIC SYLLABLE FYA' as Description,'Ethiopic' as grouping union 
select N'፠' as syllable,4960 as syllable_decimal, N'፠' as syllable_v2,'1360' as syllable_hex,'ETHIOPIC SECTION MARK' as Description,'Ethiopic' as grouping union 
select N'፡' as syllable,4961 as syllable_decimal, N'፡' as syllable_v2,'1361' as syllable_hex,'ETHIOPIC WORDSPACE' as Description,'Ethiopic' as grouping union 
select N'።' as syllable,4962 as syllable_decimal, N'።' as syllable_v2,'1362' as syllable_hex,'ETHIOPIC FULL STOP' as Description,'Ethiopic' as grouping union 
select N'፣' as syllable,4963 as syllable_decimal, N'፣' as syllable_v2,'1363' as syllable_hex,'ETHIOPIC COMMA' as Description,'Ethiopic' as grouping union 
select N'፤' as syllable,4964 as syllable_decimal, N'፤' as syllable_v2,'1364' as syllable_hex,'ETHIOPIC SEMICOLON' as Description,'Ethiopic' as grouping union 
select N'፥' as syllable,4965 as syllable_decimal, N'፥' as syllable_v2,'1365' as syllable_hex,'ETHIOPIC COLON' as Description,'Ethiopic' as grouping union 
select N'፦' as syllable,4966 as syllable_decimal, N'፦' as syllable_v2,'1366' as syllable_hex,'ETHIOPIC PREFACE COLON' as Description,'Ethiopic' as grouping union 
select N'፧' as syllable,4967 as syllable_decimal, N'፧' as syllable_v2,'1367' as syllable_hex,'ETHIOPIC QUESTION MARK' as Description,'Ethiopic' as grouping union 
select N'፨' as syllable,4968 as syllable_decimal, N'፨' as syllable_v2,'1368' as syllable_hex,'ETHIOPIC PARAGRAPH SEPARATOR' as Description,'Ethiopic' as grouping union 
select N'፩' as syllable,4969 as syllable_decimal, N'፩' as syllable_v2,'1369' as syllable_hex,'ETHIOPIC DIGIT ONE' as Description,'Ethiopic' as grouping union 
select N'፪' as syllable,4970 as syllable_decimal, N'፪' as syllable_v2,'136A' as syllable_hex,'ETHIOPIC DIGIT TWO' as Description,'Ethiopic' as grouping union 
select N'፫' as syllable,4971 as syllable_decimal, N'፫' as syllable_v2,'136B' as syllable_hex,'ETHIOPIC DIGIT THREE' as Description,'Ethiopic' as grouping union 
select N'፬' as syllable,4972 as syllable_decimal, N'፬' as syllable_v2,'136C' as syllable_hex,'ETHIOPIC DIGIT FOUR' as Description,'Ethiopic' as grouping union 
select N'፭' as syllable,4973 as syllable_decimal, N'፭' as syllable_v2,'136D' as syllable_hex,'ETHIOPIC DIGIT FIVE' as Description,'Ethiopic' as grouping union 
select N'፮' as syllable,4974 as syllable_decimal, N'፮' as syllable_v2,'136E' as syllable_hex,'ETHIOPIC DIGIT SIX' as Description,'Ethiopic' as grouping union 
select N'፯' as syllable,4975 as syllable_decimal, N'፯' as syllable_v2,'136F' as syllable_hex,'ETHIOPIC DIGIT SEVEN' as Description,'Ethiopic' as grouping union 
select N'፰' as syllable,4976 as syllable_decimal, N'፰' as syllable_v2,'1370' as syllable_hex,'ETHIOPIC DIGIT EIGHT' as Description,'Ethiopic' as grouping union 
select N'፱' as syllable,4977 as syllable_decimal, N'፱' as syllable_v2,'1371' as syllable_hex,'ETHIOPIC DIGIT NINE' as Description,'Ethiopic' as grouping union 
select N'፲' as syllable,4978 as syllable_decimal, N'፲' as syllable_v2,'1372' as syllable_hex,'ETHIOPIC NUMBER TEN' as Description,'Ethiopic' as grouping union 
select N'፳' as syllable,4979 as syllable_decimal, N'፳' as syllable_v2,'1373' as syllable_hex,'ETHIOPIC NUMBER TWENTY' as Description,'Ethiopic' as grouping union 
select N'፴' as syllable,4980 as syllable_decimal, N'፴' as syllable_v2,'1374' as syllable_hex,'ETHIOPIC NUMBER THIRTY' as Description,'Ethiopic' as grouping union 
select N'፵' as syllable,4981 as syllable_decimal, N'፵' as syllable_v2,'1375' as syllable_hex,'ETHIOPIC NUMBER FORTY' as Description,'Ethiopic' as grouping union 
select N'፶' as syllable,4982 as syllable_decimal, N'፶' as syllable_v2,'1376' as syllable_hex,'ETHIOPIC NUMBER FIFTY' as Description,'Ethiopic' as grouping union 
select N'፷' as syllable,4983 as syllable_decimal, N'፷' as syllable_v2,'1377' as syllable_hex,'ETHIOPIC NUMBER SIXTY' as Description,'Ethiopic' as grouping union 
select N'፸' as syllable,4984 as syllable_decimal, N'፸' as syllable_v2,'1378' as syllable_hex,'ETHIOPIC NUMBER SEVENTY' as Description,'Ethiopic' as grouping union 
select N'፹' as syllable,4985 as syllable_decimal, N'፹' as syllable_v2,'1379' as syllable_hex,'ETHIOPIC NUMBER EIGHTY' as Description,'Ethiopic' as grouping union 
select N'፺' as syllable,4986 as syllable_decimal, N'፺' as syllable_v2,'137A' as syllable_hex,'ETHIOPIC NUMBER NINETY' as Description,'Ethiopic' as grouping union 
select N'፻' as syllable,4987 as syllable_decimal, N'፻' as syllable_v2,'137B' as syllable_hex,'ETHIOPIC NUMBER HUNDRED' as Description,'Ethiopic' as grouping union 
select N'፼' as syllable,4988 as syllable_decimal, N'፼' as syllable_v2,'137C' as syllable_hex,'ETHIOPIC NUMBER TEN THOUSAND' as Description,'Ethiopic' as grouping 

select * From geez